package com.epita.airlineapi.model;

// JPA annotations for JPA usage
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

@Entity
@Getter
@Setter
@NoArgsConstructor // Required by JPA
@AllArgsConstructor
@ToString
public class MilesReward {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idReward; // You need a unique ID for this specific reward entry


    // Foreign key mapping
    // JPA sees the type: Client
    // JPA finds the ID: It finds the Primary Key of Client, which is the inherited userId (the value).
    @ManyToOne // Many rewards can belong to One client; This annotation then requires a @OneToMany(mappedBy = "client") annotation in the Client class; the value of mappedBy is the class variable name that is related to it.
    @JoinColumn(name = "client_id") // This tells the DB to use the client id as mapped to.
    private Client client;  // Using object is easier to access the id of the client because you just use its getter

    // Foreign key mapping
    @ManyToOne
    @JoinColumn(name = "flight_id")
    private Flight flight;

    @Column(name = "reward_date")
    private LocalDate date;


    @Override
    public final boolean equals(Object o) {
        if (this == o) return true; // Check memory address identity
        if (!(o instanceof MilesReward)) return false; // Check class type (handles proxies correctly)

        MilesReward that = (MilesReward) o;

        // Critical: Use Getters for 'that' because it might be a Hibernate Proxy
        // If IDs are null, they are not equal unless they are the same object (handled by first check)
        return idReward != null && idReward.equals(that.getIdReward());
    }

    @Override
    public final int hashCode() {
        // Return a constant value (or the Class hash) to prevent the HashCode
        // from changing when the ID is generated by the database.
        return getClass().hashCode();
    }
    // Constructors, Getters, Setters generated automatically by Lombok library
}

